-- Oracle SQL Script for Project Management Application

CREATE TABLE departments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    name VARCHAR2(255) NOT NULL,
    department_id NUMBER,
    FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE projects (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description CLOB,
    owner_id NUMBER,
    status VARCHAR2(50) CHECK (status IN ('geplant', 'aktiv', 'archiviert')),
    department_id NUMBER,
    FOREIGN KEY (owner_id) REFERENCES users(id),
    FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE components (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER,
    type VARCHAR2(50) NOT NULL,
    details CLOB,
    cost NUMBER,
    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE subprojects (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id NUMBER,
    name VARCHAR2(255) NOT NULL,
    status VARCHAR2(50) CHECK (status IN ('geplant', 'aktiv', 'archiviert')),
    FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE cloud_services (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    type VARCHAR2(50) NOT NULL,
    cost NUMBER
);